sudo: required
services:
  - docker

before_install:
  - docker build -t jstanley1730/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jstanley1730/client-test npm test

after_success:
  - docker build -t jstanley1730/multi-client ./client
  - docker build -t jstanley1730/multi-nginx ./nginx
  - docker build -t jstanley1730/multi-server ./server
  - docker build -t jstanley1730/multi-worker ./worker
  
  # LOGIN to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Publish to docker hub
  - docker push jstanley1730/multi-client
  - docker push jstanley1730/multi-nginx
  - docker push jstanley1730/multi-server
  - docker push jstanley1730/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-704531457592"
  bucket_path: "multi-docker"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"